blank_issues_enabled: false
contact_links:
  - name: Truefoundry Slack Community
    url: https://join.slack.com/t/truefoundry/shared_invite/zt-19h90rcfa-7NVJHJZFB587JlHoGqbRNA
    about: Please join the channel and get your queries resolved.
